cronjobs:
  scenario1:
    loadVUs: 50
    scalingDuration: 30s
    peakDuration: 250s
    jobsParallelism: 2
    scriptPath: /loadTestMoodle.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: scenario1
    image: ghcr.io/dbildungsplattform/load-test-k6:latest
  loadtestUser:
    loadVUs: 5
    scalingDuration: 5s
    peakDuration: 250s
    jobsParallelism: 1
    scriptPath: /loadtestUser.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: loadtestUser
    image: ghcr.io/dbildungsplattform/load-test-k6:latest
  browserScenario:
    loadVUs: 2
    scalingDuration: 5s
    peakSuration: 10s
    jobsParallelism: 1
    scriptPath: /browserLoadtest.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: browserScenario
    image: k6-browser:1.0 #Image not in public repo
