cronjobs:
  manager-scenario:
    jobsParallelism: 1
    scriptPath: loadtestManager.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: manager-scenario
    image: ghcr.io/dbildungsplattform/k6-loadtest:latest
    environment: moodle.test.dbildungscloud.org
  user-scenario:
    jobsParallelism: 1
    scriptPath: loadtestUser.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: user-scenario
    image: ghcr.io/dbildungsplattform/k6-loadtest:latest
    environment: moodle.test.dbildungscloud.org
  browser-scenario:
    jobsParallelism: 1
    scriptPath: browserLoadtest.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: browser-scenario
    image: ghcr.io/dbildungsplattform/k6-browser-loadtest:latest
    environment: moodle.test.dbildungscloud.org