cronjobs:
  manager-scenario:
    loadVUs: 2
    scalingDuration: 5s
    peakDuration: 25s
    jobsParallelism: 1
    scriptPath: loadtestManager.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: manager-scenario
    image: ghcr.io/dbildungsplattform/k6-loadtest:latest
  user-scenario:
    loadVUs: 5
    scalingDuration: 5s
    peakDuration: 25s
    jobsParallelism: 1
    scriptPath: loadtestUser.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: user-scenario
    image: ghcr.io/dbildungsplattform/k6-loadtest:latest
  browser-scenario:
    loadVUs: 1
    scalingDuration: 10s
    peakDuration: 50s
    jobsParallelism: 1
    scriptPath: browserLoadtest.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: browser-scenario
    image: ghcr.io/dbildungsplattform/k6-browser-loadtest:latest