cronjobs:
  manager-scenario:
    loadVUs: 15
    scalingDuration: 60s
    peakDuration: 300s
    jobsParallelism: 1
    scriptPath: loadtestManager.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: manager-scenario
    image: ghcr.io/dbildungsplattform/k6-loadtest:latest
    environment: moodle.test.dbildungscloud.org
  user-scenario:
    loadVUs: 50
    scalingDuration: 30s
    peakDuration: 300s
    jobsParallelism: 1
    scriptPath: loadtestUser.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: user-scenario
    image: ghcr.io/dbildungsplattform/k6-loadtest:latest
    environment: moodle.test.dbildungscloud.org
  browser-scenario:
    loadVUs: 1
    scalingDuration: 10s
    peakDuration: 20s
    jobsParallelism: 1
    scriptPath: browserLoadtest.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: browser-scenario
    image: ghcr.io/dbildungsplattform/k6-browser-loadtest:latest
    environment: moodle.test.dbildungscloud.org