cronjobs:
  scenario1:
    loadVUs: 50
    scalingDuration: 30s
    peakDuration: 30s
    jobsParallelism: 2
    scriptPath: /loadTestMoodle.js
    schedule: 0 8 * * *
    port: 5656
  scenario2:
    loadVUs: 12
    scalingDuration: 5s
    peakDuration: 15s
    jobsParallelism: 1
    scriptPath: /smallTest.js
    schedule: 0 8 * * *
    port: 5656
  scenario3:
    loadVUs: 0