cronjobs:
  scenario1:
    loadVUs: 50
    scalingDuration: 30s
    peakDuration: 250s
    jobsParallelism: 2
    scriptPath: /loadTestMoodle.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: scenario1
  scenario2:
    loadVUs: 5
    scalingDuration: 5s
    peakDuration: 250s
    jobsParallelism: 1
    scriptPath: /smallTest.js
    schedule: 0 8 * * *
    port: 5656
    serviceName: scenario2