apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-moodle-loadtest
  namespace: loadtest
data:
  loadtestManager.js: |-
{{ .Files.Get "tests/loadtestManager.js" | indent 4}}
  loadtestUser.js: |-
{{ .Files.Get "tests/loadtestUser.js" | indent 4}}
  browserLoadtest.js: |-
{{ .Files.Get "tests/browserLoadtest.js" | indent 4}}