apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-Moodle-Loadtest
  namespace: loadtest
data:
  loadTestMoodle.js: |-
{{ .Files.Get "js/loadtestManager.js" | indent 4}}
  loadtestUser.js: |-
{{ .Files.Get "js/loadtestUser.js" | indent 4}}
  browserLoadtest.js: |-
{{ .Files.Get "js/browserLoadtest.js" | indent 4}}