{{- range $job_name, $job_options := .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: loadtest-{{ $job_name }}
  namespace: loadtest
spec:
  schedule: {{ $job_options.schedule }}
  suspend: true
  jobTemplate:
    spec:
      completions: {{ $job_options.jobsParallelism }}
      parallelism: {{ $job_options.jobsParallelism }}
      template:
        metadata:
          labels:
            test: loadtest-{{ $job_options.serviceName }}
            pod: {{ $job_name }}
        spec:
          containers:
          - name: {{ $job_name }}
            image: {{ $job_options.image }}
            imagePullPolicy: Always
            env:
              - name: SECRET_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: vminsert-credentials
                    key: username
              - name: SECRET_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: vminsert-credentials
                    key: password
              - name: OPTIONS_FILE_PATH
                value: 300s100u.json
            args:
              ['run', '-u', '0',
                         '/scripts/{{ $job_options.scriptPath }}',
                         '--tag','NAME={{ $job_options.serviceName }}',
                         '--out', 'experimental-prometheus-rw',
                         '-e', 'ENVIRONMENT={{ $job_options.environment }}']
            volumeMounts:
            - name: config-scripts
              mountPath: /scripts
            - name: config-data
              mountPath: /data
            - name: secret-volume
              mountPath: /secrets
              readOnly: true
            - name: config-options
              mountPath: /options
            ports:
            - containerPort: {{ $job_options.port }}
              name: loadtest-pod
          volumes:
          - name: config-scripts
            configMap:
              name: configmap-moodle-loadtest
          - name: config-data
            configMap:
              name: configmap-moodle-data
          - name: secret-volume
            secret:
              secretName: login-secret
          - name: config-options
            configMap:
              name: configmap-moodle-options
          restartPolicy: OnFailure
---
{{- end}}