apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-moodle-data
  namespace: loadtest
data:
  coursetemplate.json: |-
{{ .Files.Get "data/courseParameters.json" | indent 4}}
  announcementtemplate.json: |-
{{ .Files.Get "data/announcementParameters.json" | indent 4}}