apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-moodle-data
  namespace: loadtest
data:
  coursetemplate.json: |-
{{ .Files.Get "loadtest/data/courseParameters.json" | indent 4}}
  announcementtemplate.json: |-
{{ .Files.Get "loadtest/data/announcementParameters.json" | indent 4}}
  commenttemplate.json: |-
{{ .Files.Get "loadtest/data/commentParameters.json" | indent 4}}