apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loadtest-moodle
  namespace: loadtest
  labels:
    serviceMonitorSelector: loadtest
spec:
  endpoints:
  - interval: 15s
    port: loadtest-pod
  namespaceSelector:
    matchNames:
    - loadtest
  selector:
    matchLabels:
      service: loadtest