apiVersion: v1
kind: Secret
metadata:
  name: login-secret
  namespace: loadtest
type: Opaque
stringData:
  userlogin.json: |-
{{ .Files.Get "loadtest/tests/userLogin.json" | indent 4}}
  managerlogin.json: |-
{{ .Files.Get "loadtest/tests/managerLogin.json" | indent 4}}