apiVersion: v1
kind: Secret
metadata:
  name: login-secret
  namespace: loadtest
type: Opaque
stringData:
  userlogin.json: |-
{{ .Files.Get "js/userLogin.json" | indent 4}}
  managerlogin.json: |-
{{ .Files.Get "js/managerLogin.json" | indent 4}}