apiVersion: v1
kind: Secret
metadata:
  name: login-secret
  namespace: loadtest
type: Opaque
stringData:
  userlogin.json: |-
{{ .Files.Get "tests/userLogin.json" | indent 4}}
  managerlogin.json: |-
{{ .Files.Get "tests/managerLogin.json" | indent 4}}