apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-moodle-options
  namespace: loadtest
data:
  30s1u.json: |-
{{ .Files.Get "loadtest/config/options/30s1u.json" | indent 4}}
  60s20u.json: |-
{{ .Files.Get "loadtest/config/options/60s20u.json" | indent 4}}
  300s100u.json: |-
{{ .Files.Get "loadtest/config/options/300s100u.json" | indent 4}}
  300s250u.json: |-
{{ .Files.Get "loadtest/config/options/300s250u.json" | indent 4}}
