name: Build and push k6-loadtest-exporter Image

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  pre_build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Filter Tag name
        uses: olegtarasov/get-tag@v2.1
        id: tag
        with:
          tagRegex: "(?<tag>[0-9]+.[0-9]+.[0-9]+)"

  build_and_push:
    needs: pre_build
    uses: hpi-schul-cloud/infra-tools/.github/workflows/build-and-push.yaml@master
    with:
      registry: ghcr.io
      image: dbildungsplattform/load-test-k6
      tag: ${{ needs.pre_build.outputs.tag }}
  
